services:
  - docker

before_install:
 - docker pull fauberso/archi

script:
 - make

deploy:
  provider: pages
  local_dir: html_report
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
